// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function SaveFileDialog():Promise<string>;
