// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultPath() {
  return window['go']['internal']['App']['DefaultPath']();
}

export function OpenDirectoryDialog() {
  return window['go']['internal']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['internal']['App']['OpenFileDialog']();
}

export function OpenURL(arg1) {
  return window['go']['internal']['App']['OpenURL'](arg1);
}

export function RandId() {
  return window['go']['internal']['App']['RandId']();
}

export function SaveFileDialog() {
  return window['go']['internal']['App']['SaveFileDialog']();
}

export function Version() {
  return window['go']['internal']['App']['Version']();
}
