// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog() {
  return window['go']['internal']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['internal']['App']['OpenFileDialog']();
}

export function SaveFileDialog() {
  return window['go']['internal']['App']['SaveFileDialog']();
}
