// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Dec(arg1) {
  return window['go']['srvs']['Encrypt']['Base64Dec'](arg1);
}

export function Base64Enc(arg1) {
  return window['go']['srvs']['Encrypt']['Base64Enc'](arg1);
}

export function DecryptFile(arg1, arg2) {
  return window['go']['srvs']['Encrypt']['DecryptFile'](arg1, arg2);
}

export function EncryptFile(arg1, arg2) {
  return window['go']['srvs']['Encrypt']['EncryptFile'](arg1, arg2);
}

export function HexDec(arg1) {
  return window['go']['srvs']['Encrypt']['HexDec'](arg1);
}

export function HexEnc(arg1) {
  return window['go']['srvs']['Encrypt']['HexEnc'](arg1);
}

export function Hmac(arg1, arg2, arg3) {
  return window['go']['srvs']['Encrypt']['Hmac'](arg1, arg2, arg3);
}

export function Md5(arg1) {
  return window['go']['srvs']['Encrypt']['Md5'](arg1);
}

export function Md5File(arg1) {
  return window['go']['srvs']['Encrypt']['Md5File'](arg1);
}

export function OctDec(arg1) {
  return window['go']['srvs']['Encrypt']['OctDec'](arg1);
}

export function OctEnc(arg1) {
  return window['go']['srvs']['Encrypt']['OctEnc'](arg1);
}

export function OpenSSLAesDec(arg1, arg2) {
  return window['go']['srvs']['Encrypt']['OpenSSLAesDec'](arg1, arg2);
}

export function OpenSSLAesEnc(arg1, arg2) {
  return window['go']['srvs']['Encrypt']['OpenSSLAesEnc'](arg1, arg2);
}

export function Sha1(arg1) {
  return window['go']['srvs']['Encrypt']['Sha1'](arg1);
}

export function Sha1File(arg1) {
  return window['go']['srvs']['Encrypt']['Sha1File'](arg1);
}

export function Sha224(arg1) {
  return window['go']['srvs']['Encrypt']['Sha224'](arg1);
}

export function Sha224File(arg1) {
  return window['go']['srvs']['Encrypt']['Sha224File'](arg1);
}

export function Sha256(arg1) {
  return window['go']['srvs']['Encrypt']['Sha256'](arg1);
}

export function Sha256File(arg1) {
  return window['go']['srvs']['Encrypt']['Sha256File'](arg1);
}

export function Sha384(arg1) {
  return window['go']['srvs']['Encrypt']['Sha384'](arg1);
}

export function Sha384File(arg1) {
  return window['go']['srvs']['Encrypt']['Sha384File'](arg1);
}

export function Sha512(arg1) {
  return window['go']['srvs']['Encrypt']['Sha512'](arg1);
}

export function Sha512File(arg1) {
  return window['go']['srvs']['Encrypt']['Sha512File'](arg1);
}

export function Sha512_224(arg1) {
  return window['go']['srvs']['Encrypt']['Sha512_224'](arg1);
}

export function Sha512_256(arg1) {
  return window['go']['srvs']['Encrypt']['Sha512_256'](arg1);
}

export function UnicodeDec(arg1) {
  return window['go']['srvs']['Encrypt']['UnicodeDec'](arg1);
}

export function UnicodeEnc(arg1) {
  return window['go']['srvs']['Encrypt']['UnicodeEnc'](arg1);
}

export function UrlDec(arg1) {
  return window['go']['srvs']['Encrypt']['UrlDec'](arg1);
}

export function UrlEnc(arg1) {
  return window['go']['srvs']['Encrypt']['UrlEnc'](arg1);
}

export function Utf16Dec(arg1) {
  return window['go']['srvs']['Encrypt']['Utf16Dec'](arg1);
}

export function Utf16Enc(arg1) {
  return window['go']['srvs']['Encrypt']['Utf16Enc'](arg1);
}
