// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Dec(arg1:string):Promise<string>;

export function Base64Enc(arg1:string):Promise<string>;

export function DecryptFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DefaultDecryptFilePath(arg1:string):Promise<Array<string>>;

export function DefaultEncryptFilePath(arg1:string):Promise<Array<string>>;

export function EncryptFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function HexDec(arg1:string):Promise<string>;

export function HexEnc(arg1:string):Promise<string>;

export function Hmac(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Md5(arg1:string):Promise<string>;

export function Md5File(arg1:string):Promise<string>;

export function OctDec(arg1:string):Promise<string>;

export function OctEnc(arg1:string):Promise<string>;

export function OpenSSLAesDec(arg1:string,arg2:string):Promise<string>;

export function OpenSSLAesEnc(arg1:string,arg2:string):Promise<string>;

export function Sha1(arg1:string):Promise<string>;

export function Sha1File(arg1:string):Promise<string>;

export function Sha224(arg1:string):Promise<string>;

export function Sha224File(arg1:string):Promise<string>;

export function Sha256(arg1:string):Promise<string>;

export function Sha256File(arg1:string):Promise<string>;

export function Sha384(arg1:string):Promise<string>;

export function Sha384File(arg1:string):Promise<string>;

export function Sha512(arg1:string):Promise<string>;

export function Sha512File(arg1:string):Promise<string>;

export function Sha512_224(arg1:string):Promise<string>;

export function Sha512_256(arg1:string):Promise<string>;

export function UnicodeDec(arg1:string):Promise<string>;

export function UnicodeEnc(arg1:string):Promise<string>;

export function UrlDec(arg1:string):Promise<string>;

export function UrlEnc(arg1:string):Promise<string>;

export function Utf16Dec(arg1:string):Promise<string>;

export function Utf16Enc(arg1:string):Promise<string>;
