// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Crop(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string,arg7:string):Promise<void>;

export function Decode(arg1:string):Promise<any>;

export function OpenFileDialog():Promise<string>;
