// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {srvs} from '../models';

export function Clean():Promise<void>;

export function CropAndSave(arg1:srvs.ImageOptions):Promise<void>;

export function Decode(arg1:string):Promise<srvs.ImageInfo>;

export function OpenFileDialog():Promise<string>;

export function QrDecode(arg1:Array<number>):Promise<string>;

export function QrEncode(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;
