// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {srvs} from '../models';

export function Decode(arg1:string):Promise<srvs.ImageInfo>;

export function OpenFileDialog():Promise<string>;
