// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clean() {
  return window['go']['srvs']['Image']['Clean']();
}

export function Crop(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['srvs']['Image']['Crop'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CropGif(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['srvs']['Image']['CropGif'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function Decode(arg1) {
  return window['go']['srvs']['Image']['Decode'](arg1);
}

export function OpenFileDialog() {
  return window['go']['srvs']['Image']['OpenFileDialog']();
}

export function QrDecode(arg1) {
  return window['go']['srvs']['Image']['QrDecode'](arg1);
}

export function QrEncode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['srvs']['Image']['QrEncode'](arg1, arg2, arg3, arg4, arg5);
}
