// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clean() {
  return window['go']['srvs']['Image']['Clean']();
}

export function CropAndSave(arg1) {
  return window['go']['srvs']['Image']['CropAndSave'](arg1);
}

export function Decode(arg1) {
  return window['go']['srvs']['Image']['Decode'](arg1);
}

export function OpenFileDialog() {
  return window['go']['srvs']['Image']['OpenFileDialog']();
}

export function QrDecode(arg1) {
  return window['go']['srvs']['Image']['QrDecode'](arg1);
}

export function QrEncode(arg1, arg2, arg3, arg4) {
  return window['go']['srvs']['Image']['QrEncode'](arg1, arg2, arg3, arg4);
}
