// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decode(arg1) {
  return window['go']['srvs']['Image']['Decode'](arg1);
}

export function OpenFileDialog() {
  return window['go']['srvs']['Image']['OpenFileDialog']();
}
