// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Dec(arg1) {
  return window['go']['main']['App']['Base64Dec'](arg1);
}

export function Base64Enc(arg1) {
  return window['go']['main']['App']['Base64Enc'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HexDec(arg1) {
  return window['go']['main']['App']['HexDec'](arg1);
}

export function HexEnc(arg1) {
  return window['go']['main']['App']['HexEnc'](arg1);
}

export function Md5(arg1) {
  return window['go']['main']['App']['Md5'](arg1);
}

export function OctDec(arg1) {
  return window['go']['main']['App']['OctDec'](arg1);
}

export function OctEnc(arg1) {
  return window['go']['main']['App']['OctEnc'](arg1);
}

export function OpenSSLAesDec(arg1, arg2) {
  return window['go']['main']['App']['OpenSSLAesDec'](arg1, arg2);
}

export function OpenSSLAesEnc(arg1, arg2) {
  return window['go']['main']['App']['OpenSSLAesEnc'](arg1, arg2);
}

export function Sha1(arg1) {
  return window['go']['main']['App']['Sha1'](arg1);
}

export function Sha256(arg1) {
  return window['go']['main']['App']['Sha256'](arg1);
}

export function UrlDec(arg1) {
  return window['go']['main']['App']['UrlDec'](arg1);
}

export function UrlEnc(arg1) {
  return window['go']['main']['App']['UrlEnc'](arg1);
}
